# Generated by Django 3.2.13 on 2024-08-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
