# Generated by Django 3.2.13 on 2024-08-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('production_capacity', models.IntegerField(blank=True, null=True)),
                ('production_schedule', models.TextField(blank=True, null=True)),
                ('products_produced', models.TextField(blank=True, null=True)),
                ('quality_control_procedures', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
